<div style="background: linear-gradient(90deg, #2c3e50, #3498db); 
            padding: 20px; border-radius: 10px; text-align:center;">
    <h1 style="color:white; font-family:Trebuchet MS, sans-serif; font-size:40px;">
        📊 Machine Learning Analysis 🚀
    </h1>
    <p style="color:#ecf0f1; font-size:26px; margin-top:10px;  text-align:center;">
        Simple Imputer
    </p>
</div>


In [1]:
import numpy as np 
import pandas as pd
import warnings
warnings.filterwarnings(ignore")

In [3]:
miles = pd.DataFrame({'farthest_run_mi' :[50,62,np.nan,100,26,13,31,50]})

In [4]:
miles

,farthest_run_mi
0,50.0
1,62.0
2,NaN
3,100.0
4,26.0
5,13.0
6,31.0
7,50.0


In [7]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [8]:
from sklearn.impute import SimpleImputer

In [15]:
imp_mean = SimpleImputer(strategy='mean')

In [16]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [19]:
imp_median = SimpleImputer(strategy='median')

In [21]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [22]:
imp_most_frequent = SimpleImputer(strategy='most_frequent')

In [23]:
imp_most_frequent.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

#### NAME

In [27]:
names = pd.DataFrame({'names' :['ryan', 'nolan', 'honus', 'wagner', np.nan, 'ruth']})

In [32]:
imp_constant_cat = SimpleImputer(strategy='constant', fill_value = 'missing_name')

In [33]:
imp_constant_cat.fit_transform(names)

array([['ryan'],
       ['nolan'],
       ['honus'],
       ['wagner'],
       ['missing_name'],
       ['ruth']], dtype=object)

In [34]:
imp_add_indicator = SimpleImputer(strategy='mean', add_indicator = True)

In [35]:
imp_add_indicator.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [36]:
from sklearn.compose import make_column_transformer

In [37]:
ct = make_column_transformer(
(imp_constant_cat, ['']),
(imp_mean, ['']),
remainder='drop')

In [38]:
ct.set_output(transform="pandas")

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='missing_name',
                                               strategy='constant'),
                                 ['Name']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['farthest_run_mi'])])

In [ ]:
df = ct.fit_transform(df)

<div style="background-color:#f9f9f9; border-top:6px solid #3498db; 
            padding:20px; border-radius:8px; text-align:center; margin-top:40px;">
    <h2 style="color:#2c3e50; font-family:Arial, sans-serif;">
        ✅ End of Notebook
    </h2>
    <p style="font-size:16px; color:#34495e; text-align:center;"">
        Thank you for reviewing this analysis.<br>
        🚀 Keep experimenting, keep learning!
    </p>
</div>
